name: Manually trigger workflow to update locales list

permissions:
  contents: write
  pull-requests: write

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-11
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        xcode: ["13.0"]
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get the current date for PR title
      run: echo "current_date=$(date +"%m-%d-%Y")" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script to check the locales lists
      run: python check-locales-lists.py
    - name: Update the list of locales
      run: |-
        git diff || (git add l10n-screenshots-config.yml)
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        committer: GitHub <noreply@github.com>
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: change-in-locales${{ env.current_date }}
        title: "change-in-locales-${{ env.current_date }}"
        branch: change-in-locales-${{ env.current_date }}
        body: "This (automated) PR checks if the list of locales changes"
